export const Question = [
  {
    prompt: 'Which exercise works the triceps?',
    optionA: 'Squats',
    optionB: 'Bicep curls',
    optionC: 'Bench press',
    optionD: 'Pull ups',
    answer: 'C',
  },
  {
    prompt: 'Who is the fastest man alive?',
    optionA: 'Elon Musk',
    optionB: 'Usain Bolt',
    optionC: 'Ryan Renolds',
    optionD: 'Floyd Mayweather Jr',
    answer: 'B',
  },
  {
    prompt: 'How many Wimbledon championships has Serena Williams won?',
    optionA: '7',
    optionB: '12',
    optionC: '3',
    optionD: '4',
    answer: 'A',
  },
  {
    prompt: 'Who was the 2021 Classic Mr Olympia?',
    optionA: 'Breon Ansley',
    optionB: 'Arnold Schwarzenegger',
    optionC: 'Chris Bumstead',
    optionD: 'Ronnie Coleman',
    answer: 'C',
  },
  {
    prompt: 'Which team has won the most premier league titles?',
    optionA: 'Manchester United',
    optionB: 'Manchester City',
    optionC: 'Liverpool',
    optionD: 'Leicester City',
    answer: 'A',
  },
  {
    prompt: "How many Ballon d'Or awards does Lionel Messi have?",
    optionA: '7',
    optionB: '9',
    optionC: '5',
    optionD: '3',
    answer: 'A',
  },
  {
    prompt: "How many Ballon d'Or awards does Cristiano Ronaldo have?",
    optionA: '6',
    optionB: '7',
    optionC: '2',
    optionD: '5',
    answer: 'D',
  },
]
