export const Question = [
  {
    prompt: 'Which exercise works the triceps?',
    optionA: 'Squats',
    optionB: 'Bicep curls',
    optionC: 'Bench press',
    optionD: 'Pull ups',
    answer: 'C',
  },
  {
    prompt: 'Who is the fastest man alive?',
    optionA: 'Elon Musk',
    optionB: 'Usain Bolt',
    optionC: 'Ryan Renolds',
    optionD: 'Floyd Mayweather Jr',
    answer: 'B',
  },
  {
    prompt: 'How many Wimbledon championships has Serena Williams won?',
    optionA: '7',
    optionB: '12',
    optionC: '3',
    optionD: '4',
    answer: 'A',
  },
  {
    prompt: 'Who was the 2021 Classic Mr Olympia?',
    optionA: 'Breon Ansley',
    optionB: 'Arnold Schwarzenegger',
    optionC: 'Chris Bumstead',
    optionD: 'Ronnie Coleman',
    answer: 'C',
  },
  {
    prompt: 'Which team has won the most premier league titles?',
    optionA: 'Manchester United',
    optionB: 'Manchester City',
    optionC: 'Liverpool',
    optionD: 'Leicester City',
    answer: 'A',
  },
  {
    prompt: "How many Ballon d'Or awards does Lionel Messi have?",
    optionA: '7',
    optionB: '9',
    optionC: '5',
    optionD: '3',
    answer: 'A',
  },
  {
    prompt: "How many Ballon d'Or awards does Cristiano Ronaldo have?",
    optionA: '6',
    optionB: '7',
    optionC: '2',
    optionD: '5',
    answer: 'D',
  },
  {
    prompt: 'How many years are there between each Olympics?',
    optionA: '1',
    optionB: '8',
    optionC: '4',
    optionD: '2',
    answer: 'C',
  },
  {
    prompt: 'Which country walks out first at The Olympics opening ceremony?',
    optionA: 'Italy',
    optionB: 'Greece',
    optionC: 'USA',
    optionD: 'Japan',
    answer: 'B',
  },
  {
    prompt: 'What is the national sport of Canada?',
    optionA: 'Soccer',
    optionB: 'Ice Hockey',
    optionC: 'Lacrosse',
    optionD: 'American Football',
    answer: 'C',
  },
  {
    prompt: 'What does NBA stand for?',
    optionA: 'National Basketball Association',
    optionB: 'Non Baseball Area',
    optionC: 'Neat Badminton Association',
    optionD: 'Nationwide Basketball Association',
    answer: 'A',
  },
  {
    prompt: 'What type of race is the Tour de France?',
    optionA: 'Car race',
    optionB: 'Motorcycle race',
    optionC: 'Skateboarding race',
    optionD: 'Bicycle race',
    answer: 'D',
  },
  {
    prompt: 'What is the only sport to be played on the moon?',
    optionA: 'Basketball',
    optionB: 'Golf',
    optionC: 'Cricket',
    optionD: 'Football',
    answer: 'B',
  },
  {
    prompt: 'Who was the first WNBA player to dunk in a playoff game?',
    optionA: 'Sue Bird',
    optionB: 'Brittney Griner',
    optionC: 'Candace Parker',
    optionD: 'Liz Cambage',
    answer: 'B',
  },
  {
    prompt: 'What is the very center of a target called in archery or darts?',
    optionA: 'Pin point',
    optionB: 'Mark',
    optionC: 'Jackpot',
    optionD: 'Bullseye',
    answer: 'D',
  },
  {
    prompt: 'In baseball how many strikes before the umpire calls out?',
    optionA: '3',
    optionB: '1',
    optionC: '5',
    optionD: '6',
    answer: 'A',
  },
  {
    prompt: 'Which sport did Michael Jordan leave basketball to play?',
    optionA: 'Football',
    optionB: 'Golf',
    optionC: 'Baseball',
    optionD: 'Chess',
    answer: 'C',
  },
  {
    prompt: 'Who was nicknamed The black mamba?',
    optionA: 'Cristiano Ronaldo',
    optionB: 'Megan Rapinoe',
    optionC: 'Tiger Woods',
    optionD: 'Kobe Bryant',
    answer: 'D',
  },
  {
    prompt: 'What sport features in the film "Cool runnings"?',
    optionA: 'Bobsleighing',
    optionB: 'Kayaking',
    optionC: 'Diving',
    optionD: 'Darts',
    answer: 'A',
  },
  {
    prompt: 'How many Olympic gold medals did Michael Phelps win?',
    optionA: '12',
    optionB: '18',
    optionC: '23',
    optionD: '44',
    answer: 'C',
  },
]
